services:
    vgr.core.event.entity.chart:
        class: VideoGamesRecords\CoreBundle\EventListener\Entity\ChartListener
        tags:
            - { name: doctrine.orm.entity_listener }

    vgr.core.event.entity.game:
        class: VideoGamesRecords\CoreBundle\EventListener\Entity\GameListener
        arguments:
            - '@event_dispatcher'
        tags:
            - { name: doctrine.orm.entity_listener }

    vgr.core.event.entity.group:
        class: VideoGamesRecords\CoreBundle\EventListener\Entity\GroupListener
        tags:
            - { name: doctrine.orm.entity_listener }

    vgr.core.event.entity.player_badge:
        class: VideoGamesRecords\CoreBundle\EventListener\Entity\PlayerBadgeListener
        arguments:
            - '@event_dispatcher'
        tags:
            - { name: doctrine.orm.entity_listener }

    vgr.core.event.entity.player_chart:
        class: VideoGamesRecords\CoreBundle\EventListener\Entity\PlayerChartListener
        arguments:
            - '@vgr.core.manager.score_manager'
        tags:
            - { name: doctrine.orm.entity_listener }

    vgr.core.event.entity.player:
        class: VideoGamesRecords\CoreBundle\EventListener\Entity\PlayerListener
        tags:
            - { name: doctrine.orm.entity_listener }

    vgr.core.event.entity.proof:
        class: VideoGamesRecords\CoreBundle\EventListener\Entity\ProofListener
        arguments:
            - '@vgr.core.security.user_provider'
            - '@event_dispatcher'
        tags:
            - { name: doctrine.orm.entity_listener }

    vgr.core.event.entity.proof_request:
        class: VideoGamesRecords\CoreBundle\EventListener\Entity\ProofRequestListener
        arguments:
            - '@vgr.core.security.user_provider'
            - '@event_dispatcher'
        tags:
            - { name: doctrine.orm.entity_listener }

    vgr.core.event.entity.rule:
        class: VideoGamesRecords\CoreBundle\EventListener\Entity\RuleListener
        arguments:
            - '@vgr.core.security.user_provider'
        tags:
            - { name: doctrine.orm.entity_listener }

    vgr.core.event.entity.serie:
        class: VideoGamesRecords\CoreBundle\EventListener\Entity\SerieListener
        arguments:
            - '@vgr.core.ranking.command.player.player_serie'
        tags:
            - { name: doctrine.orm.entity_listener }

    vgr.core.event.entity.team:
        class: VideoGamesRecords\CoreBundle\EventListener\Entity\TeamListener
        arguments:
            - '@vgr.core.security.user_provider'
        tags:
            - { name: doctrine.orm.entity_listener }

    vgr.core.event.entity.team_badge:
        class: VideoGamesRecords\CoreBundle\EventListener\Entity\TeamBadgeListener
        arguments:
            - '@event_dispatcher'
        tags:
            - { name: doctrine.orm.entity_listener }

    vgr.core.event.entity.team_request:
        class: VideoGamesRecords\CoreBundle\EventListener\Entity\TeamRequestListener
        tags:
            - { name: doctrine.orm.entity_listener }

    vgr.core.event.entity.video:
        class: VideoGamesRecords\CoreBundle\EventListener\Entity\VideoListener
        arguments:
            - '@vgr.core.security.user_provider'
            - '@vgr.core.data_provider.youtube'
            - '@translator'
        tags:
            - { name: doctrine.orm.entity_listener }

    vgr.core.event.entity.video_comment:
        class: VideoGamesRecords\CoreBundle\EventListener\Entity\VideoCommentListener
        arguments:
            - '@vgr.core.security.user_provider'
        tags:
            - { name: doctrine.orm.entity_listener }




