services:
    # Badges [BEGIN]
    VideoGamesRecords\CoreBundle\EventSubscriber\Badge\SetBadgeTitleSubscriber:
        class: VideoGamesRecords\CoreBundle\EventSubscriber\Badge\SetBadgeTitleSubscriber
        arguments:
            - '@translator'
            - '@vgr.core.manager.badge'
        tags: [ { name: 'kernel.event_subscriber' } ]

    VideoGamesRecords\CoreBundle\EventSubscriber\Badge\UpdatePlayerMasterBadgeSubscriber:
        class: VideoGamesRecords\CoreBundle\EventSubscriber\Badge\UpdatePlayerMasterBadgeSubscriber
        arguments:
            - '@vgr.core.handler.badge.player_game'
        tags: [ { name: 'kernel.event_subscriber' } ]

    VideoGamesRecords\CoreBundle\EventSubscriber\Badge\UpdateTeamMasterBadgeSubscriber:
        class: VideoGamesRecords\CoreBundle\EventSubscriber\Badge\UpdateTeamMasterBadgeSubscriber
        arguments:
            - '@vgr.core.handler.badge.team_game'
        tags: [ { name: 'kernel.event_subscriber' } ]

    VideoGamesRecords\CoreBundle\EventSubscriber\Badge\UpdatePlayerCountryBadgeSubscriber:
        class: VideoGamesRecords\CoreBundle\EventSubscriber\Badge\UpdatePlayerCountryBadgeSubscriber
        arguments:
            - '@vgr.core.handler.badge.player_country'
        tags: [ { name: 'kernel.event_subscriber' } ]

    VideoGamesRecords\CoreBundle\EventSubscriber\Badge\UpdatePlayerPlatformBadgeSubscriber:
        class: VideoGamesRecords\CoreBundle\EventSubscriber\Badge\UpdatePlayerPlatformBadgeSubscriber
        arguments:
            - '@vgr.core.handler.badge.player_platform'
        tags: [ { name: 'kernel.event_subscriber' } ]

    VideoGamesRecords\CoreBundle\EventSubscriber\Badge\UpdatePlayerSerieBadgeSubscriber:
        class: VideoGamesRecords\CoreBundle\EventSubscriber\Badge\UpdatePlayerSerieBadgeSubscriber
        arguments:
            - '@vgr.core.handler.badge.player_serie'
        tags: [ { name: 'kernel.event_subscriber' } ]

    VideoGamesRecords\CoreBundle\EventSubscriber\Badge\UpdateTeamSerieBadgeSubscriber:
        class: VideoGamesRecords\CoreBundle\EventSubscriber\Badge\UpdateTeamSerieBadgeSubscriber
        arguments:
            - '@vgr.core.handler.badge.team_serie'
        tags: [ { name: 'kernel.event_subscriber' } ]
    # Badges [END]

    # Update rank [BEGIN]
    VideoGamesRecords\CoreBundle\EventSubscriber\Ranking\UpdatePlayerRankSubscriber:
        class: VideoGamesRecords\CoreBundle\EventSubscriber\Ranking\UpdatePlayerRankSubscriber
        arguments:
            - '@vgr.core.ranking.command.rank_update.player'
        tags: [ { name: 'kernel.event_subscriber' } ]

    VideoGamesRecords\CoreBundle\EventSubscriber\Ranking\UpdateTeamRankSubscriber:
        class: VideoGamesRecords\CoreBundle\EventSubscriber\Ranking\UpdateTeamRankSubscriber
        arguments:
            - '@vgr.core.ranking.command.rank_update.team'
        tags: [ { name: 'kernel.event_subscriber' } ]
    # Update rank [END]

    VideoGamesRecords\CoreBundle\EventSubscriber\InsertLostPositionSubscriber:
        class: VideoGamesRecords\CoreBundle\EventSubscriber\InsertLostPositionSubscriber
        arguments:
            - '@doctrine.orm.entity_manager'
        tags: [ { name: 'kernel.event_subscriber' } ]

    VideoGamesRecords\CoreBundle\EventSubscriber\ScoreSetValueSubscriber:
        class:  VideoGamesRecords\CoreBundle\EventSubscriber\ScoreSetValueSubscriber
        tags: [ { name: 'kernel.event_subscriber'} ]

    VideoGamesRecords\CoreBundle\EventSubscriber\CanAskProofSubscriber:
        class: VideoGamesRecords\CoreBundle\EventSubscriber\CanAskProofSubscriber
        arguments:
            - '@translator'
            - '@vgr.core.data_provider.can_ask_proof'
            - '@vgr.core.security.user_provider'
        tags: [ { name: 'kernel.event_subscriber' } ]

    VideoGamesRecords\CoreBundle\EventSubscriber\IsValidTeamRequestSubscriber:
        class: VideoGamesRecords\CoreBundle\EventSubscriber\IsValidTeamRequestSubscriber
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@translator'
        tags: [ { name: 'kernel.event_subscriber' } ]

    VideoGamesRecords\CoreBundle\EventSubscriber\MajGameSubscriber:
        class: VideoGamesRecords\CoreBundle\EventSubscriber\MajGameSubscriber
        arguments:
            - '@vgr.core.manager.game'
        tags: [ { name: 'kernel.event_subscriber' } ]





