services:

  #RankUpdate
  vgr.core.ranking.command.rank_update.player:
    class: VideoGamesRecords\CoreBundle\Ranking\Command\RankUpdate\PlayerRankUpdateHandler
    arguments:
      - '@doctrine.orm.entity_manager'

  vgr.core.ranking.command.rank_update.team:
    class: VideoGamesRecords\CoreBundle\Ranking\Command\RankUpdate\TeamRankUpdateHandler
    arguments:
      - '@doctrine.orm.entity_manager'

  #Score
  vgr.core.ranking.command.scoring_player:
    class: VideoGamesRecords\CoreBundle\Ranking\Command\ScoringPlayerRankingHandler
    arguments:
      - '@doctrine.orm.entity_manager'
      - '@vgr.core.ranking.command.player.player_chart'
      - '@vgr.core.ranking.command.player.player_group'
      - '@vgr.core.ranking.command.player.player_game'
      - '@vgr.core.ranking.command.player.player_serie'
      - '@vgr.core.ranking.command.player.player'
      - '@event_dispatcher'

  vgr.core.ranking.command.scoring_team:
    class: VideoGamesRecords\CoreBundle\Ranking\Command\ScoringTeamRankingHandler
    arguments:
      - '@doctrine.orm.entity_manager'
      - '@vgr.core.ranking.command.team.team_chart'
      - '@vgr.core.ranking.command.team.team_group'
      - '@vgr.core.ranking.command.team.team_game'
      - '@vgr.core.ranking.command.team.team'
      - '@event_dispatcher'


  #Player
  vgr.core.ranking.command.player.player_chart:
    class: VideoGamesRecords\CoreBundle\Ranking\Command\Player\PlayerChartRankingHandler
    arguments:
      - '@doctrine.orm.entity_manager'
      - '@event_dispatcher'
    calls:
      - [ setPlayerChartRankingProvider, [ '@vgr.core.ranking.provider.player.player_chart' ] ]

  vgr.core.ranking.command.player.player_country:
    class: VideoGamesRecords\CoreBundle\Ranking\Command\Player\PlayerCountryRankingHandler
    arguments:
      - '@doctrine.orm.entity_manager'
      - '@event_dispatcher'

  vgr.core.ranking.command.player.player_game:
    class: VideoGamesRecords\CoreBundle\Ranking\Command\Player\PlayerGameRankingHandler
    arguments:
      - '@doctrine.orm.entity_manager'
      - '@event_dispatcher'

  vgr.core.ranking.command.player.player_group:
    class: VideoGamesRecords\CoreBundle\Ranking\Command\Player\PlayerGroupRankingHandler
    arguments:
      - '@doctrine.orm.entity_manager'
      - '@event_dispatcher'

  vgr.core.ranking.command.player.player_platform:
    class: VideoGamesRecords\CoreBundle\Ranking\Command\Player\PlayerPlatformRankingHandler
    arguments:
      - '@doctrine.orm.entity_manager'
      - '@event_dispatcher'

  vgr.core.ranking.command.player.player:
    class: VideoGamesRecords\CoreBundle\Ranking\Command\Player\PlayerRankingHandler
    arguments:
      - '@doctrine.orm.entity_manager'
      - '@event_dispatcher'

  vgr.core.ranking.command.player.player_serie:
    class: VideoGamesRecords\CoreBundle\Ranking\Command\Player\PlayerSerieRankingHandler
    arguments:
      - '@doctrine.orm.entity_manager'
      - '@event_dispatcher'

  #Team
  vgr.core.ranking.command.team.team_chart:
    class: VideoGamesRecords\CoreBundle\Ranking\Command\Team\TeamChartRankingHandler
    arguments:
      - '@doctrine.orm.entity_manager'
      - '@event_dispatcher'

  vgr.core.ranking.command.team.team_game:
    class: VideoGamesRecords\CoreBundle\Ranking\Command\Team\TeamGameRankingHandler
    arguments:
      - '@doctrine.orm.entity_manager'
      - '@event_dispatcher'

  vgr.core.ranking.command.team.team_group:
    class: VideoGamesRecords\CoreBundle\Ranking\Command\Team\TeamGroupRankingHandler
    arguments:
      - '@doctrine.orm.entity_manager'
      - '@event_dispatcher'

  vgr.core.ranking.command.team.team_serie:
    class: VideoGamesRecords\CoreBundle\Ranking\Command\Team\TeamSerieRankingHandler
    arguments:
      - '@doctrine.orm.entity_manager'
      - '@event_dispatcher'

  vgr.core.ranking.command.team.team:
    class: VideoGamesRecords\CoreBundle\Ranking\Command\Team\TeamRankingHandler
    arguments:
      - '@doctrine.orm.entity_manager'
      - '@event_dispatcher'




