VideoGamesRecords\CoreBundle\Entity\Badge:
  attributes:
    id:
      groups:
        - 'badge:read'
    type:
      groups:
        - 'badge:read'
    title:
      groups:
        - 'badge:read'
    picture:
      groups:
        - 'badge:read'
    value:
      groups:
        - 'badge:read'


