VideoGamesRecords\CoreBundle\Entity\ChartLib:
  attributes:
    id:
      groups:
        - 'chart-lib:read'
    name:
      groups:
        - 'chart-lib:read'
    type:
      groups:
        - 'chart-lib:type'
