VideoGamesRecords\CoreBundle\Entity\GameDay:
  attributes:
    id:
      groups:
        - 'game-day:read'
    day:
      groups:
        - 'game-day:read'
    game:
      groups:
        - 'game-day:read'
