VideoGamesRecords\CoreBundle\Entity\Game:
  attributes:
    id:
      groups:
        - 'game:read'
    name:
      groups:
        - 'game:read'
    picture:
      groups:
        - 'game:read'
    groups:
      groups:
        - 'game.groups'
    status:
      groups:
        - 'game:read'
    publishedAt:
      groups:
        - 'game:read'
    isRank:
      groups:
        - 'game:read'
    nbChart:
      groups:
        - 'game:read'
    nbPost:
      groups:
        - 'game:read'
    nbPlayer:
      groups:
        - 'game:read'
    nbTeam:
      groups:
        - 'game:read'
    serie:
      groups:
        - 'game:serie'
    platforms:
      groups:
        - 'game:platforms'
    rules:
      groups:
        - 'game:rules'
    slug:
      groups:
        - 'game:read'
    forum:
      groups:
        - 'game:forum'
    downloadUrl:
      groups:
        - 'game:read'
    lastUpdate:
      groups:
        - 'game:read'
    lastScore:
      groups:
        - 'game:last-score'