VideoGamesRecords\CoreBundle\Entity\Group:
  attributes:
    id:
      groups:
        - 'group:read'
    name:
      groups:
        - 'group:read'
    game:
      groups:
        - 'group:game'
    isDlc:
      groups:
        - 'group:read'
    nbChart:
      groups:
        - 'group:read'
    nbPost:
      groups:
        - 'group:read'
    nbPlayer:
      groups:
        - 'group:read'
    slug:
      groups:
        - 'group:read'
