VideoGamesRecords\CoreBundle\Entity\Group:
  attributes:
    id:
      groups:
        - 'group.list'
        - 'group.read'
        - 'group.read.mini'
    name:
      groups:
        - 'group.list'
        - 'group.read'
        - 'group.read.mini'
    game:
      groups:
        - 'group.game'
    isDlc:
      groups:
        - 'group.list'
    nbChart:
      groups:
        - 'group.list'
        - 'group.read'
    nbPost:
      groups:
        - 'group.list'
        - 'group.read'
    nbPlayer:
      groups:
        - 'group.list'
        - 'group.read'
    slug:
      groups:
        - 'group.list'
        - 'group.read'
        - 'group.read.mini'
    createdAt:
      groups: []
    updatedAt:
      groups: []
