VideoGamesRecords\CoreBundle\Entity\Player:
  attributes:
    id:
      groups:
        - 'player.read'
        - 'player.read.mini'
        - 'player.put'
    pseudo:
      groups:
        - 'player.read'
        - 'player.read.mini'
    createdAt:
      groups:
        - 'player.read'
    lastLogin:
      groups:
        - 'player.read'
    nbConnexion:
      groups:
        - 'player.read'
    presentation:
      groups:
        - 'player.read'
        - 'player.put'
    collection:
      groups:
        - 'player.read'
        - 'player.put'
    slug:
      groups:
        - 'player.read'
        - 'player.read.mini'
    status:
      groups:
        - 'player.status'
    avatar:
      groups:
        - 'player.read'
        - 'player.read.mini'
    country:
      groups:
        - 'player.country'
        - 'player.put'
    rankCountry:
      groups:
        - 'player.read'
    rankPointChart:
      groups:
        - 'player.pointChart'
    averageChartRank:
      groups:
        - 'player.pointChart'
    nbChart:
      groups:
        - 'player.pointChart'
        - 'player.proof'
    nbChartMax:
      groups:
        - 'player.pointChart'
    nbChartWithPlatform:
      groups:
        - 'player.pointChart'
    nbChartProven:
      groups:
        - 'player.pointChart'
        - 'player.proof'
    nbChartDisabled:
      groups:
        - 'player.pointChart'
        - 'player.proof'
    pointChart:
      groups:
        - 'player.pointChart'
    rankPointGame:
      groups:
        - 'player.pointGame'
    pointGame:
      groups:
        - 'player.pointGame'
    nbGame:
      groups:
        - 'player.pointGame'
    rankMedal:
      groups:
        - 'player.medal'
    chartRank0:
      groups:
        - 'player.medal'
    chartRank1:
      groups:
        - 'player.medal'
    chartRank2:
      groups:
        - 'player.medal'
    chartRank3:
      groups:
        - 'player.medal'
    rankCup:
      groups:
        - 'player.cup'
    averageGameRank:
      groups:
        - 'player.cup'
    gameRank0:
      groups:
        - 'player.cup'
    gameRank1:
      groups:
        - 'player.cup'
    gameRank2:
      groups:
        - 'player.cup'
    gameRank3:
      groups:
        - 'player.cup'
    rankProof:
      groups:
        - 'player.proof'
    rankBadge:
      groups:
        - 'player.badge'
    pointBadge:
      groups:
        - 'player.badge'
    nbMasterBadge:
      groups:
        - 'player.badge'
    team:
      groups:
        - 'player.team'
        - 'player.put'
        - 'player.profile'
    birthDate:
      groups:
        - 'player.read'
        - 'player.put'
    gender:
      groups:
        - 'player.read'
        - 'player.put'
    website:
      groups:
        - 'player.read'
        - 'player.put'
    youtube:
      groups:
        - 'player.read'
        - 'player.put'
    twitch:
      groups:
        - 'player.read'
        - 'player.put'
    displayPersonalInfos:
      groups:
        - 'player.read'
        - 'player.put'
    lastDisplayLostPosition:
      groups:
        - 'player.put'
