VideoGamesRecords\CoreBundle\Entity\PlayerPlatform:
  attributes:
    player:
      groups:
        - 'player-platform:player'
    platform:
      groups:
        - 'player-platform:platform'
    rankPointPlatform:
      groups:
        - 'player-platform:read'
    pointPlatform:
      groups:
        - 'player-platform:read'
    nbChart:
      groups:
        - 'player-platform:read'

