ProjetNormandie\UserBundle\Entity\User:
  attributes:
    id:
      groups:
        - 'user:read'
    username:
      groups:
        - 'user:read'
    status:
      groups:
        - 'user:read'
    lastLogin:
      groups:
        - 'user:read'
    nbConnexion:
      groups:
        - 'user:read'
    nbForumMessage:
      groups:
        - 'user:read'
    createdAt:
      groups:
        - 'user:read'



