VideoGamesRecords\CoreBundle\Entity\VideoComment:
  attributes:
    id:
      groups:
        - 'video-comment:read'
    video:
      groups:
        - 'video-comment:insert'
    player:
      groups:
        - 'video-comment:player'
    text:
      groups:
        - 'video-comment:read'
        - 'video-comment:insert'
    createdAt:
      groups:
        - 'video-comment:read'
