VideoGamesRecords\CoreBundle\Entity\Video:
  attributes:
    id:
      groups:
        - 'video:read'
    libVideo:
      groups:
        - 'video:read'
        - 'video:insert'
        - 'video:update'
    slug:
      groups:
        - 'video:read'
    status:
      groups:
        - 'video:read'
    type:
      groups:
        - 'video:read'
    externalId:
      groups:
        - 'video:read'
    url:
      groups:
        - 'video:read'
        - 'video:insert'
    tag:
      groups:
        - 'video:insert'
        - 'video:update'
    title:
      groups:
        - 'video:read'
    description:
      groups:
        - 'video:read'
    viewCount:
      groups:
        - 'video:read'
    likeCount:
      groups:
        - 'video:read'
    thumbnail:
      groups:
        - 'video:read'
    nbComment:
      groups:
        - 'video:read'
    game:
      groups:
        - 'video:game'
        - 'video:insert'
    player:
      groups:
        - 'video:player'
    createdAt:
      groups:
        - 'video:read'