resources:
    VideoGamesRecords\CoreBundle\Entity\Country:
        collectionOperations:
            get:
                normalization_context: {'groups': [country.read]}
        itemOperations:
            get:
                normalization_context: {'groups': [country.read]}
            player-ranking-points:
                method: 'GET'
                normalization_context: { 'groups': [player.read,team.read.mini,player.pointGame,player.pointChart] }
                path: '/countries/{id}/ranking'
                swagger_context:
                    parameters:
                        - name: id
                          in: path
                          required: true
                          type: integer
                        - name: maxRank
                          in: query
                          required: false
                          type: integer
                controller: 'VideoGamesRecords\CoreBundle\Controller\Country\GetRanking'