resources:
    VideoGamesRecords\CoreBundle\Entity\Group:
        attributes:
            pagination_enabled: false
        subresourceOperations:
            api_games_groups_get_subresource:
                method: 'GET'
                normalization_context: {'groups': [group.list]}
        collectionOperations:
            get:
                normalization_context: {'groups': [group.list]}
        itemOperations:
            get:
                normalization_context: {'groups': [group.read]}
            form-data:
                method: 'GET'
                normalization_context:
                    groups: [ chart.read, chart.group, group.read.mini, chart.libs, chartLib.read, chart.playerCharts, playerChart.read, playerChart.chart, playerChart.player, playerChart.libs, playerChart.status, playerChartStatus.read, playerChart.platform ]
                    enable_max_depth': true
                    subresource_operation_name: ''
                access_control: 'is_granted("ROLE_PLAYER")'
                path: '/groups/{id}/form-data'
                swagger_context:
                    parameters:
                        -   name: id
                            in: path
                            required: true
                            type: integer
                        -   name: libChart
                            in: query
                            required: false
                            type: string
                controller: 'VideoGamesRecords\CoreBundle\Controller\Group\GetFormData'
            player-ranking-points:
                method: 'GET'
                normalization_context: {'groups': [playerGroup.pointChart,playerGroup.player,player.read.mini,player.team,team.read.mini,player.country,country.read]}
                path: '/groups/{id}/player-ranking-points'
                swagger_context:
                    parameters:
                        - name: id
                          in: path
                          required: true
                          type: integer
                        - name: maxRank
                          in: query
                          required: false
                          type: integer
                controller: 'VideoGamesRecords\CoreBundle\Controller\Group\Player\GetRankingPoints'
            player-ranking-medals:
                method: 'GET'
                normalization_context: {'groups': [playerGroup.medal,playerGroup.player,player.read.mini,player.team,team.read.mini,player.country,country.read]}
                path: '/groups/{id}/player-ranking-medals'
                swagger_context:
                    parameters:
                        - name: id
                          in: path
                          required: true
                          type: integer
                        - name: maxRank
                          in: query
                          required: false
                          type: integer
                controller: 'VideoGamesRecords\CoreBundle\Controller\Group\Player\GetRankingMedals'
            team-ranking-points:
                method: 'GET'
                normalization_context: {'groups': [teamGroup.pointChart, teamGroup.team, team.read.mini]}
                path: '/groups/{id}/team-ranking-points'
                swagger_context:
                    parameters:
                        - name: id
                          in: path
                          required: true
                          type: integer
                        - name: maxRank
                          in: query
                          required: false
                          type: integer
                controller: 'VideoGamesRecords\CoreBundle\Controller\Group\Team\GetRankingPoints'
            team-ranking-medals:
                method: 'GET'
                normalization_context: {'groups': [teamGroup.medal, teamGroup.team, team.read.mini]}
                path: '/groups/{id}/team-ranking-medals'
                swagger_context:
                    parameters:
                        - name: id
                          in: path
                          required: true
                          type: integer
                        - name: maxRank
                          in: query
                          required: false
                          type: integer
                controller: 'VideoGamesRecords\CoreBundle\Controller\Group\Team\GetRankingMedals'
            top-score:
                method: 'GET'
                normalization_context: {'groups': [chart.read, chart.top-score, playerChart.libs, playerChartLib.format, playerChart.read, playerChart.player, player.read.mini]}
                path: '/groups/{id}/top-score'
                swagger_context:
                    parameters:
                        - name: id
                          in: path
                          required: true
                          type: integer
                controller: 'VideoGamesRecords\CoreBundle\Controller\Group\GetTopScore'
        properties:
            charts:
                subresource:
                    resourceClass: 'VideoGamesRecords\CoreBundle\Entity\Chart'
                    collection: true