resources:
    VideoGamesRecords\CoreBundle\Entity\Serie:
        collectionOperations:
            get:
                normalization_context: {'groups': [serie.list]}
        itemOperations:
            get:
                normalization_context: {'groups': [serie.read]}
            player-ranking-points:
                method: 'GET'
                normalization_context: { 'groups': [ playerSerie.pointChart,playerSerie.player,player.read.mini,player.team,team.read.mini,player.country,country.read ] }
                path: '/series/{id}/player-ranking-points'
                swagger_context:
                    parameters:
                        -   name: id
                            in: path
                            required: true
                            type: integer
                        -   name: maxRank
                            in: query
                            required: false
                            type: integer
                controller: 'VideoGamesRecords\CoreBundle\Controller\Serie\Player\GetRankingPoints'
            player-ranking-medals:
                method: 'GET'
                normalization_context: { 'groups': [ playerSerie.medal,playerSerie.player,player.read.mini,player.team,team.read.mini,player.country,country.read ] }
                path: '/series/{id}/player-ranking-medals'
                swagger_context:
                    parameters:
                        -   name: id
                            in: path
                            required: true
                            type: integer
                        -   name: maxRank
                            in: query
                            required: false
                            type: integer
                controller: 'VideoGamesRecords\CoreBundle\Controller\Serie\Player\GetRankingMedals'